### ISSUE TITLE
Matching icon

### ISSUE THREAD

**Issue by apals** [armada-ths/armada-android#52]
We need an icon that conveys the purpose of the matching functionality. A heart would probably be the easiest, but we use this for Favorites. Thoughts? @Jeppes @kyriaki93 @mfrisell

**Comment by kyriaki93** [comment]
I think the heart is a good matching icon, so maybe if we change the favorite icon to a star?

**Comment by apals** [comment]
@Jeppes

**Comment by Jeppes** [comment]
@apals sorry bout the delay. Using stars might be an option, but since the icon will be so prevalent in the list I think it's going to look pretty strange. I'll give it a try when I get a change and post some screenshots so we can decide what we like most
